name: spherical-ml-biodiversity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.2
  - healpy=1.18
  - cartopy=0.24
  - matplotlib=3.10
  - scipy
  - pyproj
  - jupytext
  - nbclient
  - ipykernel
  - jupyter
  - xarray=2025.4
  - netcdf4
  - dask
  - pandas
  - cftime
  - pip:
      - zenodo-get
      - h3
      - pygbif
